### ISSUE TITLE
Redundant recursive error in MCPlatformSupport class>>#redefineSubclassesOf:using:

### ISSUE THREAD

**Issue by rjsargent** [GsDevKit/GsDevKit#106]
MCPlatformSupport class>>#redefineSubclassesOf:using: appears to redundantly call itself recusrively.

	(aClassOrganizer subclassesOf: aClass) do: [:subClass | | newClass |
		newClass := _subClass definition evaluate_.
		**self redefineSubclassesOf: subClass using: aClassOrganizer**.
	].

Evaluating a class definition, as shown in the italicised line, ends up invoking this method for each of its subclasses and in turn for each of theirs. This means that by the time the recursive invocation runs (bold), all the class' subclasses have already been "recompiled".

For a sufficiently shallow hierarchy, there are no obvious ill effects. However, by the time you get to a three-level deep hierarchy, the subclass definition expression omits the symbol dictionary name because the recursive code is working with a version of the class which is no longer the one that can be resolved from the user's symbol list.

I will follow up with additional comments elaborating on what my tracing showed.

**Comment by rjsargent** [comment]
The class hierarchy I was working with looked like the following, with * indicating which one I had added an instance variable to.
A ( ... )
*	B ( ... )
		C ( ... )
			D1 ( ... )
			D2 ( ... )

The following logs show how one of the "D" classes is handled, then how the "C" class is, and finally how the "B" class is, as far as it gets before the lack of a symbol dictionary manifests.

1) Leaf class change

Redefining RepPortalEmailTraxitResendPrompt* 16r2841B54701 under RepPortalEmailTraxitPrompt* 16r284679BD01
New Version RepPortalEmailTraxitResendPrompt[2/2]* 16r6455401 under RepPortalEmailTraxitPrompt* 16r284679BD01
Begin Nested for  RepPortalEmailTraxitResendPrompt[1/2] 16r2841B54701 under RepPortalEmailTraxitPrompt* 16r284679BD01
	End Nesting

"Redefining" identifies the original class.
"New Version" identifies the class version produced from the modified definition.
"Begin Nested" and "End Nested" bracket the implementation in #redefineSubclassesOf:using:.
"[n/m]" identifies the class version, if there is more than one.
"*" identifies whether the class version is the one that can be resolved from the symbol list.

2) Non-leaf class (one layer below it)

Redefining RepPortalEmailTraxitPrompt* 16r284679BD01 under RepPortalTraxitEventNotePrompt* 16r2844035201
		Subclass RepPortalEmailPromptMock* 16r24F3FE01 under RepPortalEmailTraxitPrompt* 16r284679BD01
		Subclass RepPortalEmailTraxitResendPrompt* 16r2841B54701 under RepPortalEmailTraxitPrompt* 16r284679BD01
New Version RepPortalEmailTraxitPrompt[2/2]* 16r6455401 under RepPortalTraxitEventNotePrompt* 16r2844035201
Begin Nested for  RepPortalEmailTraxitPrompt[1/2] 16r284679BD01 under RepPortalTraxitEventNotePrompt* 16r2844035201
	Redefining RepPortalEmailPromptMock* 16r24F3FE01 under RepPortalEmailTraxitPrompt[1/2] 16r284679BD01
	New Version RepPortalEmailPromptMock[2/2]* 16r63EED01 under RepPortalEmailTraxitPrompt[2/2]* 16r6455401
	Begin Nested for  RepPortalEmailPromptMock[1/2] 16r24F3FE01 under RepPortalEmailTraxitPrompt[1/2] 16r284679BD01
		End Nesting
	**Begin Nested for  RepPortalEmailPromptMock[1/2] 16r24F3FE01 under RepPortalEmailTraxitPrompt[1/2] 16r284679BD01
		End Nesting**
	Redefining RepPortalEmailTraxitResendPrompt* 16r2841B54701 under RepPortalEmailTraxitPrompt[1/2] 16r284679BD01
	New Version RepPortalEmailTraxitResendPrompt[2/2]* 16r6413B01 under RepPortalEmailTraxitPrompt[2/2]* 16r6455401
	Begin Nested for  RepPortalEmailTraxitResendPrompt[1/2] 16r2841B54701 under RepPortalEmailTraxitPrompt[1/2] 16r284679BD01
		End Nesting
	**Begin Nested for  RepPortalEmailTraxitResendPrompt[1/2] 16r2841B54701 under RepPortalEmailTraxitPrompt[1/2] 16r284679BD01
		End Nesting**
	End Nesting

The bold lines show how the redundant line in the method runs it again.
"Subclass" enumerates the subclasses of the class version above it.


3) Class two-levels above the leaf

Redefining RepPortalTraxitEventNotePrompt* 16r2844035201 under RepWebComponent* 16r283F2D1901
		Subclass RepPortalEmailTraxitPrompt* 16r284679BD01 under RepPortalTraxitEventNotePrompt* 16r2844035201
New Version RepPortalTraxitEventNotePrompt[2/2]* 16r6455401 under RepWebComponent* 16r283F2D1901
Begin Nested for  RepPortalTraxitEventNotePrompt[1/2] 16r2844035201 under RepWebComponent* 16r283F2D1901
	Redefining RepPortalEmailTraxitPrompt* 16r284679BD01 under RepPortalTraxitEventNotePrompt[1/2] 16r2844035201
			Subclass RepPortalEmailPromptMock* 16r24F3FE01 under RepPortalEmailTraxitPrompt* 16r284679BD01
			Subclass RepPortalEmailTraxitResendPrompt* 16r2841B54701 under RepPortalEmailTraxitPrompt* 16r284679BD01
	New Version RepPortalEmailTraxitPrompt[2/2]* 16r643B801 under RepPortalTraxitEventNotePrompt[2/2]* 16r6455401
	Begin Nested for  RepPortalEmailTraxitPrompt[1/2] 16r284679BD01 under RepPortalTraxitEventNotePrompt[1/2] 16r2844035201
		Redefining RepPortalEmailPromptMock* 16r24F3FE01 under RepPortalEmailTraxitPrompt[1/2] 16r284679BD01
		New Version RepPortalEmailPromptMock[2/2]* 16r641F201 under RepPortalEmailTraxitPrompt[2/2]* 16r643B801
		Begin Nested for  RepPortalEmailPromptMock[1/2] 16r24F3FE01 under RepPortalEmailTraxitPrompt[1/2] 16r284679BD01
			End Nesting
		**Begin Nested for  RepPortalEmailPromptMock[1/2] 16r24F3FE01 under RepPortalEmailTraxitPrompt[1/2] 16r284679BD01
			End Nesting**
		Redefining RepPortalEmailTraxitResendPrompt* 16r2841B54701 under RepPortalEmailTraxitPrompt[1/2] 16r284679BD01
		New Version RepPortalEmailTraxitResendPrompt[2/2]* 16r6447001 under RepPortalEmailTraxitPrompt[2/2]* 16r643B801
		Begin Nested for  RepPortalEmailTraxitResendPrompt[1/2] 16r2841B54701 under RepPortalEmailTraxitPrompt[1/2] 16r284679BD01
			End Nesting
		**Begin Nested for  RepPortalEmailTraxitResendPrompt[1/2] 16r2841B54701 under RepPortalEmailTraxitPrompt[1/2] 16r284679BD01
			End Nesting**
		End Nesting
	Begin Nested for  RepPortalEmailTraxitPrompt[1/2] 16r284679BD01 under RepPortalTraxitEventNotePrompt[1/2] 16r2844035201
		Redefining RepPortalEmailPromptMock[2/2]* 16r641F201 under RepPortalEmailTraxitPrompt[2/2]* 16r643B801

At this last point, the class definition string for RepPortalEmailTraxitPrompt[1/2] has no dictionary specified, since it cannot be resolved via the symbol list. 

-------------------------
I do not know whether the redundant class recompilation can cause a problem, but the redundancy is still a problem itself.

In my original scenario, I had changed _GsPackagePolicy current homeSymbolDict_ to answer an immutable symbol dictionary. Having done this made the redundant calls throw an exception because of using the _homeSymbolDict_ as the default symbol dictionary when the class definition expression did not specify which one to use.

**Comment by rjsargent** [comment]
(And I see that my logging indentation got lost.)

**Comment by dalehenrich** [comment]
... at least restored your indentation ... when you and I are in office let's have a chat ...
