### ISSUE TITLE
Class>>#_ogDefinitionInContext:className:superClassName: inconsistency

### ISSUE THREAD

**Issue by rjsargent** [GsDevKit/GsDevKit#119]
Class>>#_ogDefinitionInContext:className:superClassName: takes a UserProfile as its first argument. It uses that argument in some places but uses System myUserProfile in other places.

It should only use the provided argument. If there is a reason for the schizophrenic use, it should document the reason.

**Comment by dalehenrich** [comment]
merged to master [a52114fb0]
