### ISSUE TITLE
Error parsing some method selectors

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit#128]
Originally reported as GsDevKit/GsDevKit_home#298 from @brunobuzzi ...

It seems there is bug in ChangeList>>parseSelector: (or Scanner>>scanMessageParts:) (tested on GS 3.5.1 & 3.5.4).
Try:
```
ChangeList parseSelector:
'myMethodName
    -1 to: 2 do: [:i |].'. 
```
But the following will work ok :
```
ChangeList parseSelector:
'myMethodName
    ||
    -1 to: 2 do: [:i |].'. 
```
So it seems a border case when you have a negative number immediately after the selector. 
The following also will fail:
```
ChangeList parseSelector:
'myMethodName
    -1 '. 
```

The workaround will be add  empty temp definition at the beginning "||" of the method.

**Comment by dalehenrich** [comment]
Looks like this bug has bee around for quite some time ... (test fails in 3.3.9)

**Comment by dalehenrich** [comment]
@brunobuzzi, I'm curious why you are working with ChangeList? GLASS doesn't use changeLists and ChangeList>>parseSelector: is no longer used in favor of `Behavior class>>parseSelector:for:` and/or `RBParser>>parseMethodPattern:` ... there are still senders, but the senders are no longer in the mainline code base of GLASS ... 

The ChangeList code and Scanner class are very ancient (likely dating back to 2007) ... If you need to use ChangeLists ... then perhaps porting the current Pharo Implementation might make more sense or using RBParser?

RBParser has been kept up-to-date because it is being used to format source in GemStone ... and will be part of Rowan, so we will likely continue to keep RBParser alive ... 

I bring all this up, because this bug has exposed a fairly serious problem in the Scanner and there doesn't seem to be a trivial solution ...

Finally:
``` smalltalk
RBParser parseMethodPattern: 'myMethodName
    -1 to: 2 do: [:i |].'
```
returns  `#'myMethodName'` as expected ...

**Comment by brunobuzzi** [comment]
Actually i have a problem loading XPath with the following expression:
```
Metacello new
	baseline: 'XPath';
	repository: 'github://brunobuzzi/XML-XPath:gemstone/filetree';
	load.
```
After some debug i reached this problem.
It seems that `MCFileTreeStCypressReader>>methodSelectorFor:` is using ChangeList.

The complete sequence it will be:
```
createStone devKit_XML354 3.5.4
"login into new stone"
Metacello new
	baseline: 'XPath';
	repository: 'github://brunobuzzi/XML-XPath:gemstone/filetree';
	load.
```
You can check the stack on the original post in the mailing list:
forum.world.st/ChangeList-parseSelector-bug-td5124016.html

**Comment by dalehenrich** [comment]
Ah, then MCFileTreeStCypressReader>>methodSelectorFor: should be changed to use RBParser or Behavior ... I'll resubmit this bug over in the Filetree project and fix it there ...

**Comment by dalehenrich** [comment]
... I hadn't actually read the original email and expected the details to show up in the bug report ... oh, well, I think I understand the issue now and the fix should be very straightforward ... closing in favor or dalehenrich/filetree#231.
