### ISSUE TITLE
list instances, triggered by auto migration could be compromised if epoch gc is enabled or an MFC is run while a list instances scan is in progress

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit#142]
Internal bug 50078  "upgradeImage (and upgradeSeasideImage?) should turn off epoch GC to avoid potential 'Voting occurred or an atomic promote detected during the operation...' errors" has highlighted the potential interruption to an auto migration and there's not much that can be done, except to abort and try again ... so this bug is being reported to help spread information about the potential problem ...

**Comment by dalehenrich** [comment]
It looks like the best option here, is to fail to start an auto migration step if epoch gc is enabled, since it is impossible to tell whether or not the list instances phase will be interrupted by a vote ... the error message a user gets (about voting) is otherwise sufficient for a vote resulting from an MFC, since the user is in control of the MFC ...

The final hole that probably needs to be plugged involves regularly scheduled MFC.s occurring during a code update ... this one is harder to handle and requires some thought and perhaps a general warning is worth putting out there ...

**Comment by jbrichau** [comment]
@dalehenrich I guess this applies to any use of `list all instances` when epoch gc is turned on? Or is this specific to the upgrade procedure?

**Comment by dalehenrich** [comment]
All usages of list instances are exposed ... and it applies to all GCs, I don't remember the precise bug, but voting while doing a list instances scan can lead to db corruption/errors, as I think that objects that are being voted down can be kept in the head of gem (the scan is oop based so it is cheaper/easier to throw an error than other alternatives) ... this is a recent bugfix (introducing the error) in 3.6.x.

I plan to do an announcement on the GLASS list, since automigration is in common usage, and doing an automigration during voting could fail and it is impossible to tell when a gc/vote might occur before the scan is finished ...so far there are no easy solutions :smile:

**Comment by dalehenrich** [comment]
@pdebruic brought up the fact that if the only consequence of the error were to need to rerun the migration that might not be that bad ... and with that thought in mind, wrapping all production code loads with `GsDeployer class>>bulkMigrate:` would defer auto migration until after the block completed execution (i.e., code load itself) and limit one's exposure to the bug to "just re-running the migration") ... 

Since upgradeSeasideImage ([GsDevKit_upgrade](https://github.com/GsDevKit/GsDevKit_upgrade)) explicitly uses `GsDeployer class>>deploy:` ... it's probably worth updating [GsDevKit_upgrade](https://github.com/GsDevKit/GsDevKit_upgrade) to use `bulkMigrate:` instead.

**Comment by dalehenrich** [comment]
`GsDeployer class>>bulkMigrate:` could also be modified to wait until voting was complete and retry the list instances scan  ... it worries me that in some corner conditions, we're at risk of not being able to finish the scan without developer intervention (i.e., turn off epoch gc) and in the cases where a single scan can take hours, I'm not sure even one retry is worth the potentially wasted time ... I think limiting the damage to leaving unmigrated class instances lying around is about the best that can be done (assuming that developers choose to take this route at all)... and developers are always free to use their own retry strategies if they so choose ...

**Comment by dalehenrich** [comment]
> @dalehenrich I guess this applies to any use of `list all instances` when epoch gc is turned on? Or is this specific to the upgrade procedure?

@jbrichau yes ... and my fix is to call waitForVoteStateIdle in McPlatformSupport class>> listInstances: which should be the method used by all listInstances use in GLASS
