### ISSUE TITLE
SmallTime>>asDuration errors (GemStone 3.6 and higher)

### ISSUE THREAD

**Issue by jbrichau** [GsDevKit/GsDevKit#144]
The implementation of `Time>>asDuration` (in https://github.com/glassdb/glass/blob/master/repository/Squeak.v36.package/Time.extension/instance/asDuration.st) accesses the instvar `milliseconds. This means the following happens:

```
Time now asDuration
```
throws:
```
ERROR 2710 , a Error occurred (error 2710), a SmallTime, instVar access not allowed in a special object, instVarAt: 0
```

There should either be an override on `SmallTime>>asDuration` or the implementation on `Time` should be:

```Smalltalk
asDuration

	^ self asMilliseconds asDuration
```

**Comment by jbrichau** [comment]
@dalehenrich I registered the issue in this repo, but all my scripts reference https://github.com/glassdb/glass
So, the fix should end up there.
However, there seems to be quite some commits difference...

What is the best approach for me to submit a fix for this?

**Comment by dalehenrich** [comment]
At one time I had a grand plan to consolidate all the projects in GsDevKit, but the logistics of replacing glassdb/glass was a bridge too far …

**Comment by jbrichau** [comment]
@dalehenrich This repo and the glassdb/glass repo have different commits/changes? Should they be different (i.e. do I submit the fix to both?)

**Comment by jbrichau** [comment]
I quickly looked at the diffs. Looks like most actual changes in this repo are about the repo location indeed. There are some others but none about code diffs. 
In the glassdb/glass repo, there are a lot more changes which are not in this repo.

Is the conclusion that this repo is stalled and the repo where I should submit the PR to is the glassdb/glass one?

**Comment by dalehenrich** [comment]
yeah glassdb/glass is the primary

**Comment by jbrichau** [comment]
Thanks for integrating the fix!
