### ISSUE TITLE
'7.3470570000000004E+02' asNumber -> 7.3470570000000004E+00

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit#20]
See discussion in the [thread](http://forum.world.st/Glass-7-3470570000000004E-02-asNumber-7-3470570000000004E-00-tp4757718.html) ...

A hack is proposed in my post, but there could/should be a cleaner solution ... in 3.2 the only remaining problem is the cap letters (as we've stopped printing floats with the $+) ...

**Comment by marianopeck** [comment]
Hi @dalehenrich. Newbie question about github...is there a way I can see a diff (in the web) of all the commits referenced in this issue? Or I must go and click one by one?  Thanks in advance

**Comment by dalehenrich** [comment]
@marianopeck since there isn't a single pull request for Issue #20, it is quite convenient ... but the fix is included as part of a [pull request](https://github.com/glassdb/glass/issues/3) and it does look like [the set of commits for Issue #20 are sequential](https://github.com/glassdb/glass/pull/3/commits) (scroll to bottom), so [comparing the first and last commits](https://github.com/glassdb/glass/compare/60da124e9c41ebe4d82cfc2471c7be1aecae6451...b76cfabd9143f31e337abdae72343dfd0f5c77c6) should give you the picture you are looking for. 

There are so many files involved, because the Squeak package has been forked a number of times ... one of these days I'll clean that up:)
