### ISSUE TITLE
Apparent hangs during HTTP downloads 

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit#60]
Without going too deeply into the gory details, this morning the internet was VERY slow and my gsDevKitHome builds were completely stalled because http downloads from certain sites were glacial ... @martinmcclure was able to point a finger at slow comcast routers. curl and wget were having trouble as well, but they weren't hanging like my build, so I looked into the timeout situation and found that HTTPSocket>>getResponseUpTo:ignoring: and HTTPSocket>>getResponseUpTo: had 120000ms timeouts ... they've been that way for 8 years, but 2 minute timeouts are a bit much .... when I cranked the timeout down to a more reasonable 500 ms I was able to finish my builds ... so I'll push this change up ... today

**Comment by krono** [comment]
You thinks that's worth back-porting to squeak?

**Comment by dalehenrich** [comment]
Is that the default timeout for Squeak? If so, then I think that it's worth putting into HTTPSocket ... it is very possible that I bumped the timeout up a long time ago ... never expecting that 2 we'd hit 2 minutes of hang time:)

**Comment by dalehenrich** [comment]
[clean build](https://travis-ci.org/glassdb/glass/builds/55402989) and I've used this branch for a number of builds and for the most part the subsequent connections complete very quickly so I haven't experienced a downside to half second delays

**Comment by krono** [comment]
(the code is very different in Squeak currently, so this does not apply. Thanks nevertheless :)

**Comment by dalehenrich** [comment]
neglected to include path for Squeak and Squeak.v3 packages ... didn't bump version for Squeak.v32 package ...

**Comment by dalehenrich** [comment]
At the end of the day the real fix was two-fold. One was to reduce the timeout ... 20s seems to be about right while 500ms can be too short ... Two was retry when a timeout caused a failure ... the retry on timeout was the key fix since that bit of logic is absolutely required for the internet ... especially in the last couple of days ... 

Putting the patch into https://github.com/GsDevKit/gsUpgrader/issues/14 so that the proper logic can be in force when starting an install ... should be enough to get to the point where the proper patch isn installed ...

**Comment by dalehenrich** [comment]
[clean build](https://travis-ci.org/glassdb/glass/builds/55590695)
