### ISSUE TITLE
Allow Transcript to print either in Gem log file or Object Log or both

### ISSUE THREAD

**Issue by marianopeck** [GsDevKit/GsDevKit#70]
See whole discussion at: http://forum.world.st/Can-I-plug-a-custom-transcript-proxy-for-one-closure-execution-td4841365.html

Source: 

	TranscriptProxy class >>  show: anObject
	    | proxy |
	 	(GsSession currentSession symbolList objectNamed: #SkipObjectLogLogging) 
	  		ifNil: [ (ObjectLogEntry transcript: anObject printString object: anObject) addToLog ].
	    (proxy := self proxyTranscript) ~~ nil
	      ifTrue: [ proxy show: anObject ]
	      ifFalse: [ 
	        (GsSession currentSession symbolList objectNamed: #SkipGemLogFileLogging) 
	          ifNil: [ GsFile gciLogServer: '--transcript--' , anObject printString ] ]

Example of usage in a particular gem:

	| skipLoggingDict symbolList |
	  skipLoggingDict := SymbolDictionary new.
	  skipLoggingDict at: #'SkipObjectLogLogging' put: Object new.
	  symbolList := GsSession currentSession symbolList.
	  symbolList add: skipLoggingDict before: UserGlobals.

**Comment by dalehenrich** [comment]
Not going to implement this feature for GemStone 2.4.x ...

**Comment by dalehenrich** [comment]
on second thought the gem-sepcific state should be put into `SessionTemps current` ... much less invasive relative to the class namespace and simpler
