### ISSUE TITLE
MAStringReader>>visitNumberDescription broken

### ISSUE THREAD

**Issue by IwanVosloo** [GsDevKit/GsDevKit#75]
This method calls NumberParser class>>isNumber: which in turn calls class side methods that are not implemented on NumberParser in GemStone (yet they are implemented on Pharo).

Observed with:
  GemStone 3.2.6 (64bit)
  Seaside 3.1.4
  Magritte 3.3.1, 3.3.2, 3.5

**Comment by marianopeck** [comment]
Hi guys,

I just found this very same issue but after reading this entry as well as the referenced issues I am still not sure how it was finally fixed. 

Magritte 3 (both, either GsDevKit repo or shub) continue doing `NumberParser isNumber: self contents.` in `MAStringReader>>visitNumberDescription`, and my latest GemStone 3.3 does not implement `NumberParser class >> isNumber`. So...where should the fix be?

Thanks in advance

**Comment by marianopeck** [comment]
For the record, I just tried upgrading GLASS just in case but still, no `isNumber:`. 

		Gofer new
		package: 'GsUpgrader-Core';
		url: 'http://ss3.gemtalksystems.com/ss/gsUpgrader';
		load.
		(Smalltalk at: #GsUpgrader)
		    upgradeGLASS;
		    upgradeGLASS1;
		    upgradeMetacello;
		    upgradeGrease.

Sure, I can add it myself to my compatibility packages...but just wanted to know if I was missing something..
