### ISSUE TITLE
FileDirectory>>exists chokes when an OS error occurs ... returns nil instead of Boolean

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit#79]
The following is the suggested patch:

```Smalltalk
exists
  | result |
  result := GsFile _exists: self pathString onClient: self onClient.
  result ifNil: [ self error: 'Disk error: ' , GsFile lastErrorString ].
  ^ result
```

**Comment by marianopeck** [comment]
Dale, 

This improves things a bit in the sense that the error is much clearer. So I would include this fix. However, it does not fix my original problem. We will continue that in the mailing list.

Anyway, in MY CASE, the `lastErrorString` answered nil, so I must also cover that case. In addition, showing the path is very useful. With that said, I think this code may be better:

	exists
	  | result |
	  result := GsFile _exists: self pathString onClient: self onClient.
	  result
	    ifNil: [ 
	      self
	        error:
	          'Disk error: ' , (GsFile lastErrorString ifNil: [ '' ]) , ' for path: '
	            , self pathString ].
	  ^ result

**Comment by dalehenrich** [comment]
Thanks, I've incorporated your suggestion .. 

I didn't think this had anything to do with fixing the post cache clear problem....
