### ISSUE TITLE
add identityIncludes:  method to Collection  class

### ISSUE THREAD

**Issue by dariogithub** [GsDevKit/GsDevKit#88]
The migration tools by Otto Behrens call this method.
It's defined into Pharo and i think it should be ported i into GLASS.

identityIncludes: anObject 
	"Answer whether anObject is one of the receiver's elements."

	self do: [:each | anObject == each ifTrue: [^true]].
	^false

**Comment by dalehenrich** [comment]
@dariogithub, GemStone already provides Collection>>includesIdentical:, so I would recommend that #identityIncludes: be implmented in terms of #includesIdentical:...
