### ISSUE TITLE
System class>>_vmInstanceCount:  no longer returns an Array of Associations and invalidates code in MCPlatformSupport class>>installAlmostOutOfMemoryStaticHandler:

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit#90]
In the current versions of GemStone, System class>>_vmInstanceCount:  returns a Boolean for this expression `System _vmInstanceCount: 3` and dumps a report to the gem log ... which is not what 
the method MCPlatformSupport class>>installAlmostOutOfMemoryStaticHandler: is expecting

**Comment by marianopeck** [comment]
And now that we can do `export GS_DEBUG_VMGC_VERBOSE_OUTOFMEM=1` I think we
may remove that code from here...

On Mon, Mar 7, 2016 at 6:38 PM, Dale Henrichs <notifications@github.com>
wrote:

> In the current versions of GemStone, System class>>_vmInstanceCount:
> returns a Boolean for this expression System _vmInstanceCount: 3 and
> dumps a report to the gem log ... which is not what
> the method MCPlatformSupport class>>installAlmostOutOfMemoryStaticHandler:
> is expecting
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GsDevKit/GsDevKit/issues/90>.
>



-- 
Mariano
http://marianopeck.wordpress.com

**Comment by dalehenrich** [comment]
Difficult to create a unit test for travis that takes a gem crash as a pass ... manual testing looks good ...
