### ISSUE TITLE
'-123' asInteger yields incorrect answer (123 rather than -123)

### ISSUE THREAD

**Issue by rjsargent** [GsDevKit/GsDevKit#94]
CharacterCollection>>#asInteger from the *squeak-converting category incorrectly excludes the '-' from what it considers the start of a numeric string.

It is also unclear whether it is intended to accept 'ABC123' and yield 123. In m opinion, that would be wrong.

**Comment by dalehenrich** [comment]
Not sure as to why it was implemented that way other than it was originally taken from the Squeak implementation 10 years ago:). SqueakTests>>testAsInteger doesn't test for  leading $-, but a more recent Pharo version of the tests (Pharo3.0) looks like the following:

```smalltalk
testAsInteger

	self assert: '1796exportFixes-tkMX' asInteger = 1796.
	self assert: 'donald' asInteger isNil.
	self assert: 'abc234def567' asInteger = 234.
	self assert: '-94' asInteger = -94.
	self assert: 'foo-bar-92' asInteger = -92
```
So there is definitely some funkiness expected by the SqueakPharo version of #asInteger...

Here's the implementation of #asSignedInteger (called by #asInteger) as of Pharo36.0:

```smalltalk
asSignedInteger 
	"Returns the first signed integer it can find or nil."

	| start stream |
	start := self findFirst: [:char | char isDigit].
	start isZero ifTrue: [^ nil].
	stream := self readStream position: start - 1.
	((stream position ~= 0) and: [stream peekBack = $-])
		ifTrue: [stream back].
	^ Integer readFrom: stream
```

**Comment by jbrichau** [comment]
Seaside3.2 and 3.3 (dev) have a failing test related to this issue [sample travis build here](https://travis-ci.org/SeasideSt/Seaside/jobs/239265550) . I propose adding `asSignedInteger` and `asUnsignedInteger` and changing `asInteger` in GsDevkit/GLASS to call `asSignedInteger`.

This would change behavior such that negative integers are read as well. People _may_ be affected, but I think this is more of a bugfix.
