### ISSUE TITLE
Squeak compatibility code for CharacterCollection>>#sameAs: is stale

### ISSUE THREAD

**Issue by rjsargent** [GsDevKit/GsDevKit#97]
The current implementation of CharacterCollection>>#sameAs: is incorrect. It is also inconsistent with other dialects. It answers true for 'no' sameAs: 'not'. Pharo, as of at least v3, VW 8.1, and GS as of 3.2 all consider a string as not the #sameAs: any shorter prefix of itself. [No idea what current Squeak implementations do.]

Since it appears to exist in the GemStone base since version 3.2.0, it can be removed from the compatibility code for recent GemStone versions. (It should be updated for older versions.)

**Comment by rjsargent** [comment]
Expected results:
('PREFIX' sameAs: 'prefix') = true.
('pref' sameAs: 'prefix') = false.
('prefixes' sameAs: 'prefix') = false.

**Comment by dalehenrich** [comment]
looks like this issue was fixed with commit be4e54327 (Mon Aug 31 17:55:08 2020 -0700)
